using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

namespace ApiServer.Controllers.Template1_Controllers
{
    [Route("api/Template1/[controller]")]
    [ApiController]
    [SwaggerTag("This is an example controller generated by ASP.NET Core 2.x - Template1")]
    public class PublicController : ControllerBase
    {
        [HttpPost]
        [SwaggerOperation(Summary ="temp", Description = "test desc", OperationId = "Post", Tags = new[] { "Template1" })]
        public void Post([FromBody] string value)
        {
        }

        [HttpGet("{id}")]
        public ActionResult<string> Get(int id)
        {
            return "value";
        }


    }
}
