namespace ApiWebServer.Models
{
    public class Const
    {
        public int iteminven_quantity;
        public int mailbox_quantity;
        public int fatigue_injury_rate;
        public int inury_rate_base;
        public int inury_rate_slightly;
        public int inury_rate_serious;
        public int inury_rate_fatal;
        public int inury_debuff_base;
        public int inury_debuff_slightly;
        public int inury_debuff_serious;
        public int inury_debuff_fatal;
        public int fatigue_slump_const;
        public int slump_debuff;
        public int matchsimulation_maxcount;
        public int matchsimulation_end_pitcherhealth;
        public int matchsimulation_end_time;
        public int intervention_att_base;
        public int intervention_def_scoregap_min;
        public int intervention_def_scoregap_max;
        public int intervention_def_teamspirit;
        public int intervention_exit_ab;
        public int intervention_wait_time;
        public int ingame_skill_waittime;
        public int ingame_tactics_waittime;
        public int ingame_shift_waittime;
        public int teamspirit_point_start;
        public int teamspirit_point_min;
        public int teamspirit_point_combo;
        public int coach_power_training_cost;
        public int leadership_open_cost_type1;
        public int leadership_open_cost_count1;
        public int leadership_open_cost_type2;
        public int leadership_open_cost_count2;
        public int leadership_reset_cost_type1;
        public int leadership_reset_cost_count1;
        public int leadership_reset_cost_type2;
        public int leadership_reset_cost_count2;
        public int potential_open_cost_type1;
        public int potential_open_cost_count1;
        public int potential_open_cost_type2;
        public int potential_open_cost_count2;
        public int potential_reset_cost_type1;
        public int potential_reset_cost_count1;
        public int potential_reset_cost_type2;
        public int potential_reset_cost_count2;
        public int leadership_rankup_cost_type;
        public int leadership_rankup_cost_count;
        public int potential_rankup_cost_type;
        public int potential_rankup_cost_count;
        public int leadership_rankup_power_const;
        public int leadership_rankup_skill_const;
        public int potential_rankup_power_const;
        public int potential_rankup_skill_const;
        public int ledership_skill_slot_open1;
        public int ledership_skill_slot_open2;
        public int ledership_skill_slot_open3;
        public int simulation_speed_x1;
        public int simulation_speed_x1_5;
        public int simulation_speed_x2;
        public int mastery_cost;
        public int mastery_cost_limit;
        public int mastery_reset_cost_type;
        public int mastery_reset_cost_count;
        public int intervention_percentup_value;
        public int intervention_percentdown_scoregap;
        public int intervention_percentdown_value;
        public int schedule_half_kbo;
        public int schedule_half_mlb;
        public int schedule_half_cpbl;
        public int schedule_half_npb;
        public int release_player_price_type;
        public int release_player_price_value;
        public int release_coach_price_type;
        public int release_coach_price_value;
        public int binder_reset_cost_type;
        public int binder_reset_cost_value;
        public int binder_reset_cost_const;
        public int binder_reset_time;
        public int binder_reset_cost_maxnum;
        public int scout_finish_const;
    }

    public class PvpConst
    {
        public int ranked_legendary_rankingstart;
        public int ranked_legendary_rankingmax;
        public int ranked_matching_rank_rng;
        public int ranked_matching_rank_minuser;
        public int ranked_matching_rank_maxuser;
        public int ranked_matching_teampower_rng;
        public int ranked_matching_teampower_minuser;
        public int ranked_matching_teampower_maxuser;
        public int ranked_matching_record_rng;
        public int ranked_matching_record_minuser;
        public int ranked_matching_record_maxuser;
        public int ranked_matching_winrate_rng;
        public int ranked_matching_winrate_minuser;
        public int ranked_matching_prevusercooltime;
        public int time_dailyreset_global;
        public int time_dailyreset_kr;
        public int time_dailyreset_us;
        public int time_dailyreset_tw;
        public int time_dailyreset_jp;
        public int streakmode_continue_costtype;
        public int streakmode_continue_cost;
        public int streakmode_continue_maxcount;

    }
}
