using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApiServer.Core.DB;
using ApiServer.Core.Swagger;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Swashbuckle.AspNetCore.Annotations;

namespace ApiServer.Controllers.Template_Controllers
{
    [Route("api/[controller]")]
    [SwaggerTag("This is administrator controller generated by ASP.NET Core 2.x - Template")]
    [ApiController]
    public class AdministratorController : ControllerBase
    {
        private readonly ILogger<AdministratorController> _logger;
        private readonly IConfiguration _config;
        private readonly IDbService _dbService;


        public AdministratorController(ILogger<AdministratorController> logger, IConfiguration config, IDbService dbService)
        {
            _logger = logger;
            _config = config;
            _dbService = dbService;
        }

        [HttpGet("{id}")]
        [ApiExplorerSettings(GroupName = "admin", IgnoreApi = false)]
        [SwaggerDescription("관리자에 의한 정보 조회")]
        public ActionResult<string> Get(int id)
        {
            // find data

            string resultData = "value";
            return resultData;
        }

        [HttpPost("Update")]
        [ApiExplorerSettings(GroupName = "admin", IgnoreApi = false)]
        [SwaggerDescription("관리자에 의한 정보 업데이트")]
        public ActionResult Update(string value)
        {
            // modify data

            return StatusCode(StatusCodes.Status200OK);
        }
    }
}
